### ISSUE TITLE
Parameter 'using: node18' is not supported

### ISSUE THREAD

**Issue by tarampampam** [JorgeLNJunior/render-deploy#17]
Just for your information:

![image](https://user-images.githubusercontent.com/7326800/202165573-507e19b2-f439-4c11-b755-4fd35ee606dd.png)

```yaml
  deploy-to-render:
    name: 🚀 Update the demo stand on render.com
    runs-on: ubuntu-latest
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.2.1
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: false
```

Workflow run: https://github.com/tarampampam/webhook-tester/actions/runs/3478776542/jobs/5816542046
